
# Site settings
title: Evan's world
email: <Your Email>
description: 个人博客 # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://xxxxx.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  Evan

# Disqus settings（https://disqus.com/）
disqus_username: 你的Username
disqus: Evan

# Build settings


permalink: /:year/:month/:day/:title.html

